export const GAME_COUNTDOWN_DURATION_MS = 4_000;

export const TURN_DURATION_MS = 30_000;

export const NEXT_TURN_TRANSITION_DELAY_MS = 3_000;

export const NEXT_ROUND_TRANSITION_DELAY_MS = 4_000;

export const PLAYER_RECONNECT_GRACE_PERIOD_MS = 15_000;
